server:
    shutdown: graceful
    port: 8081

spring:
    application:
        name: gateway-service
    profiles:
        include:
            - route
        active: dev

eureka:
    client:
        service-url:
            defaultZone: http://${discovery.id}:${discovery.password}@${discovery.ip}:8761/eureka

logging:
    level:
        org:
            springframework: DEBUG